version: 2

jobs:
  "golang-1.13":
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go get ./...
      - run: go build
      - run: go test ./...
  "golang-1.14":
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go get ./...
      - run: go build
      - run: go test ./...
  "golang-latest":
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get ./...
      - run: go build
      - run: go test ./...

workflows:
  version: 2
  build:
    jobs:
      - "golang-1.13"
      - "golang-1.14"
      - "golang-latest"
